#' Cell type annotation with OpenAI GPT models
#'
#' Cell type annotation with OpenAI GPT models
#'
#' Annotate cell types by OpenAI GPT models in a Seurat pipeline or with a custom gene list. If used in a Seurat pipeline, Seurat FindAllMarkers() function needs to be run first and the differential gene table generated by Seurat will serve as the input. If the input is a custom list of genes, one cell type is identified for each element in the list. 
#' 
#' @param input Either the differential gene table returned by Seurat FindAllMarkers() function, or a list of genes.
#' @param tissuename Optional input of tissue name.
#' @param openai_key The OpenAI key obtained from https://platform.openai.com/account/api-keys The default is NA, which will resulting outputing the prompt itself. If an actual key is provided, then the output will be the celltype annotations from the GPT model specified by the user. 
#' @param model A valid GPT-4 or GPT-3.5 model name list on https://platform.openai.com/docs/models. Default is 'gpt-4-32k'.
#' @param topgenenumber Number of top differential genes to be used if input is Seurat differential genes.
#' @import openai
#' @export
#' @return A vector of cell types when the user provide openai_key or the prompt itself when openai_key = NA (default)
#' @author Wenpin Hou <wh2526@@cumc.columbia.edu>, Zhicheng Ji <zhicheng.ji@@duke.edu>
#' @examples 
#' # Gene list as input, openai_key = NA (default)
#' prompt <- gptcelltype(input=list(gs1=c('CD4,CD3D'),gs2='CD14'),tissuename='human PBMC',openai_key=NA, model = 'gpt-4')
#' cat(prompt)
#' # Seurat object as input, openai_key = NA (default)
#' #You have to install Seurat package first to run this example
#' library(Seurat)
#' data("pbmc_small")
#' all.markers <- FindAllMarkers(object = pbmc_small)
#' prompt <- gptcelltype(all.markers, tissuename='human PBMC', openai_key=NA)
#' return(prompt)

gptcelltype <- function(input, tissuename=NULL, openai_key, model='gpt-4', topgenenumber = 10) {
  if (!is.na(openai_key)) Sys.setenv(OPENAI_API_KEY = openai_key)
  
  if (class(input)=='list') {
    input <- sapply(input,paste,collapse=',')
  } else {
    input <- tapply(input$gene,list(input$cluster),function(i) paste0(i[1:topgenenumber],collapse=','))
  }
  
  if (is.na(openai_key)){
    
    message = paste0('Identify cell types of ',tissuename,' cells using the following markers separately for each row. Only provide the cell type name. Do not show numbers before the name. Some can be a mixture of multiple cell types. ',  "\n", paste0(names(input), ':',unlist(input),collapse = "\n"))
    return(message)
    
  } else {
    cutnum <- ceiling(length(input)/30)
    if (cutnum > 1) {
      cid <- as.numeric(cut(1:length(input),cutnum))	
    } else {
      cid <- rep(1,length(input))
    }
    
    allres <- sapply(1:cutnum,function(i) {
      id <- which(cid==i)
      flag <- 0
      while (flag == 0) {
        k <- create_chat_completion(
          model = model,
          message = list(list("role" = "user", "content" = paste0('Identify cell types of ',tissuename,' cells using the following markers separately for each row. Only provide the cell type name. Do not show numbers before the name. Some can be a mixture of multiple cell types.\n',paste(input[id],collapse = '\n'))))
        )
        res <- strsplit(k$choices[,'message.content'],'\n')[[1]]
        if (length(res)==length(id))
          flag <- 1
      }
      names(res) <- names(input)[id]
      res
    },simplify = F) 
    print('It is always recommended to check the results returned by GPT-4 in case of AI hallucination, before going to down-stream analysis.')
    return(gsub(',$','',unlist(allres)))
  }
  
}
